name: Bug Report
description: Submit a bug report
title: "[Bug]: "
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        **BEFORE SUBMITTING THIS REPORT, make sure you have Geckolib installed, and that the version matches your minecraft version and mod loader! You can download it from this page: https://www.curseforge.com/minecraft/mc-mods/geckolib/files**
  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: What version of the mod are you using?
      placeholder: ex. 1.0.0
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      description: What Mod Loader are you running?
      options:
        - Fabric
        - Forge
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod Loader Version
      description: What version of the mod loader are you using?
      placeholder: ex. 40.1.25
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please give a thorough explanation of what happened. Attach/Link relevant images/files in relation to the issue!
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: latest.log
      description: Please upload your latest.log file directly here or use https://gist.github.com/ and leave the link here.
      placeholder: Drag and drop latest.log file here or link it with https://gist.github.com/!
    validations:
      required: true
