blank_issues_enabled: false
contact_links:
  - name: Starfish Studios Discord
    url: https://discord.com/invite/starfishstudios
    about: Join our discord to chat with us, ask questions, or make suggestions!
